Controllers/TranzactiiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRYPTO_Burcea.DAL;
using CRYPTO_Burcea.BLL;
using Microsoft.AspNet.Identity;
using PagedList;

namespace CRYPTO_Burcea.Controllers
{
    public class TranzactiiController : Controller
    {
        BLLOperatiiAR oBLLo = new BLLOperatiiAR();
        BLLTransfer oBLLtrans = new BLLTransfer();
        BLLTranzactionare oBLLtranz = new BLLTranzactionare();

        // GET: Tranzactii

        // Afisare tranzactii - toate felurile
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        // Afisare istoric alimentari / retrageri
        [Authorize]
        public ActionResult IstoricAR(string searchData, string searchPortofel, int? pagina)
        {
            string username = User.Identity.GetUserName();
            List<OperatiuneAR> sursadate;
            IQueryable<OperatiuneAR> sursa;
            sursa = oBLLo.AfiseazaToateOperatiile().Where(o => o.ContinutPortofel.Portofel.Utilizator.Username == username);
            if (!string.IsNullOrEmpty(searchData))
            {
                DateTime data = Convert.ToDateTime(searchData);
                sursa = oBLLo.Cauta(sursa, o => o.DataOperatiune == data);
            }
            if (!string.IsNullOrEmpty(searchPortofel))
            {
                sursa = oBLLo.Cauta(sursa, o => o.ContinutPortofel.Portofel.DenumirePortofel.Contains(searchPortofel));
            }

            sursadate = sursa.OrderByDescending(o => o.DataOperatiune).ToList();
            return PartialView("_IstoricAR", sursadate.ToPagedList(pagina ?? 1, 10));
        }

        // Afisare istoric transferuri
        [Authorize]
        public ActionResult IstoricTransferuri(string searchData, string searchPortofel, int? pagina)
        {
            string username = User.Identity.GetUserName();
            List<TransferICP> sursadate;
            IQueryable<TransferICP> sursa;
            sursa = oBLLtrans.AfiseazaTaoateTransferurile().Where(t => t.ContinutPortofel.Portofel.Utilizator.Username == username);
            if (!string.IsNullOrEmpty(searchData))
            {
                DateTime data = Convert.ToDateTime(searchData);
                sursa = oBLLtrans.Cauta(sursa, t => t.DataTransfer == data);
            }
            if (!string.IsNullOrEmpty(searchPortofel))
            {
                sursa = oBLLtrans.Cauta(sursa, t => t.ContinutPortofel.Portofel.DenumirePortofel.Contains(searchPortofel) || t.ContinutPortofel1.Portofel.DenumirePortofel.Contains(searchPortofel));
            }

            sursadate = sursa.OrderByDescending(t => t.DataTransfer).ToList();
            return PartialView("_IstoricTransferuri", sursadate.ToPagedList(pagina ?? 1, 10));
        }

        // Afisare istoric tranzactionari
        [Authorize]
        public ActionResult IstoricTranzactionari(string searchData, string searchPortofel, int? pagina)
        {
            string username = User.Identity.GetUserName();
            List<Tranzactionare> sursadate;
            IQueryable<Tranzactionare> sursa;
            sursa = oBLLtranz.AfiseazaToateTranzactionarile().Where(t => t.ContinutPortofel.Portofel.Utilizator.Username == username);
            if (!string.IsNullOrEmpty(searchData))
            {
                DateTime data = Convert.ToDateTime(searchData);
                sursa = oBLLtranz.Cauta(sursa, t => t.DataTranzactionare == data);
            }
            if (!string.IsNullOrEmpty(searchPortofel))
            {
                sursa = oBLLtranz.Cauta(sursa, t => t.ContinutPortofel.Portofel.DenumirePortofel.Contains(searchPortofel) || t.ContinutPortofel1.Portofel.DenumirePortofel.Contains(searchPortofel));
            }

            sursadate = sursa.OrderByDescending(t => t.DataTranzactionare).ToList();
            return PartialView("_IstoricTranzactionari", sursadate.ToPagedList(pagina ?? 1, 10));
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using CRYPTO_Burcea.BLL
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CRYPTO ACB</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="background-color: #FFFF8F">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CRYPTO ACB", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Portofel", "Index", "Portofel")</li>
                        <li>@Html.ActionLink("Istoric tranzacții", "Index", "Tranzactii")</li>
                        <li>@Html.ActionLink("Cryptomonede", "Index", "Moneda")</li>

                        BLLUtilizator oBLL = new BLLUtilizator();
                        if (oBLL.EsteAdmin(User.Identity.GetUserName()))
                        {
                            <li> | </li>
                            <li>@Html.ActionLink("Financiar", "Index", "Financiar")</li>
                            <li> | </li>
                            <li>@Html.ActionLink("Administrare", "Index", "Utilizator")</li>

                        }
                    }


                    <li> | </li>
                    <li>@Html.ActionLink("Despre", "About", "Home")</li>


                </ul>

                    
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CRYPTO ACB</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>