Controllers/FinanciarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRYPTO_Burcea.BLL;
using CRYPTO_Burcea.DAL;
using PagedList;

namespace CRYPTO_Burcea.Controllers
{
    public class FinanciarController : Controller
    {
        BLLFinanciar oBLL = new BLLFinanciar();
        // GET: Financiar

        // Afisare interfata pentru alegerea monedei
        [Authorize]
        public ActionResult Index()
        {
            CRYPTOEntities bd = new CRYPTOEntities();
            List<Moneda> monede = bd.Monedas.ToList();
            ViewBag.ListaMonede = monede.Select(m => new SelectListItem()
            {
                Value = m.Id.ToString(),
                Text = m.DenumireMoneda
            });
            return View();
        }

        // Detalii
        [Authorize]
        public ActionResult Detalii(Int64 idMoneda)
        {
            ViewBag.idMoneda = idMoneda;
            return PartialView("_Detalii");
        }

        // Afisare vanzari societate (cumparari client)
        [Authorize]
        public ActionResult Vanzari(Int64 idMoneda, string searchData, int? pagina)
        {
            ViewBag.id = idMoneda;
            List<Tranzactionare> sursadate;
            IQueryable<Tranzactionare> sursa;
            sursa = oBLL.Vanzari(idMoneda);

            decimal suma = 0;
            decimal comisioane = 0;
            foreach (Tranzactionare t in sursa)
            {
                suma += (decimal)t.SumaCumparata;
                comisioane += (decimal)t.ComisionEuro;
            }

            suma = Math.Round(suma, 2);
            comisioane = Math.Round(comisioane, 2);
            ViewBag.suma = suma;
            ViewBag.comisioane = comisioane;

            if (!string.IsNullOrEmpty(searchData))
            {
                DateTime data = Convert.ToDateTime(searchData);
                sursa = oBLL.Cauta(sursa, t => t.DataTranzactionare == data);
            }

            sursadate = sursa.OrderByDescending(t => t.DataTranzactionare).ToList();
            return PartialView("_Vanzari", sursadate.ToPagedList(pagina ?? 1, 10));
        }

        // Afisare cumparari societate (vanzari client)
        [Authorize]
        public ActionResult Cumparari(Int64 idMoneda, string searchData, int? pagina)
        {
            ViewBag.id = idMoneda;
            List<Tranzactionare> sursadate;
            IQueryable<Tranzactionare> sursa;
            sursa = oBLL.Cumparari(idMoneda);

            decimal suma = 0;
            decimal comisioane = 0;
            foreach (Tranzactionare t in sursa)
            {
                suma += (decimal)t.SumaVanduta;
                comisioane += (decimal)t.ComisionEuro;
            }

            suma = Math.Round(suma, 2);
            comisioane = Math.Round(comisioane, 2);
            ViewBag.suma = suma;
            ViewBag.comisioane = comisioane;

            if (!string.IsNullOrEmpty(searchData))
            {
                DateTime data = Convert.ToDateTime(searchData);
                sursa = oBLL.Cauta(sursa, t => t.DataTranzactionare == data);
            }

            sursadate = sursa.OrderByDescending(t => t.DataTranzactionare).ToList();
            return PartialView("_Cumparari", sursadate.ToPagedList(pagina ?? 1, 10));
        }

    }
}

Views/Financiar/Index.cshtml

@{
    ViewBag.Title = "Date financiare";
}

<h2>Date financiare</h2>

<script src="~/Scripts/jquery-3.4.1.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>

@using (Ajax.BeginForm("Detalii", "Financiar", new AjaxOptions()
{
    HttpMethod = "GET",
    UpdateTargetId = "divDetaliiF",
    InsertionMode = InsertionMode.Replace
}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Alege o monedă pentru a afla informații precum totalul vânzărilor și cumpărărilor de monedă, precum și comisioanele percepute</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Moneda", "Moneda", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idMoneda", new SelectList(ViewBag.ListaMonede, "Value", "Text"), "Selectati moneda", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessage("idMoneda", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Vezi rezultatele" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<hr />
<div id="divDetaliiF">

</div>

Views/Financiar/_Cumparari.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<CRYPTO_Burcea.DAL.Tranzactionare>

<script src="~/Scripts/jquery-3.4.1.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>


<p>
    Total cumpărări: <b style="color:blue">@ViewBag.suma</b>
</p>
<p>
    Total comisioane: <b>@ViewBag.comisioane euro</b>
</p>

<div class="table-bordered">
    <h4>&nbsp;Căutare</h4>


    @using (Ajax.BeginForm("Cumparari", "Financiar", new { idMoneda = ViewBag.id }, new AjaxOptions()
    {
        HttpMethod = "GET",
        UpdateTargetId = "divRezultat",
        InsertionMode = InsertionMode.Replace
    }))
    {
        <span>&nbsp;Data: </span>@Html.TextBox("searchData", null, new { @class = "form-control datepicker" })
        <input type="submit" class="btn btn-primary" value="Caută" />
    }
    <br />
</div>

<link href="~/Content/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/bootstrap-datepicker.min.js"></script>


<script>
    $('.datepicker').datepicker({
        format: 'yyyy-mm-dd'
    });
</script>


<br />


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().DataTranzactionare)
        </th>
        <th>
            @Html.DisplayName("Suma cumpărată")
        </th>
        <th>
            @Html.DisplayName("Suma corespondentă")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().ComisionEuro)
        </th>
        <th>
            @Html.DisplayName("Moneda cumpărată")
        </th>
        <th>
            @Html.DisplayName("Moneda corespondentă")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DataTranzactionare)
            </td>
            <td style="color:green">
                @Html.DisplayFor(modelItem => item.SumaVanduta)
            </td>
            <td style="color:red">
                @Html.DisplayFor(modelItem => item.SumaCumparata)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ComisionEuro)
            </td>
            <td style="color:green">
                @Html.DisplayFor(modelItem => item.Moneda.DenumireMoneda)
            </td>
            <td style="color:red">
                @Html.DisplayFor(modelItem => item.Moneda1.DenumireMoneda)
            </td>
        </tr>
    }

</table>

Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) din @Model.PageCount
@Html.PagedListPager(Model, pagina => Url.Action("Cumparari", "Financiar", new { idMoneda = ViewBag.id, pagina, searchData = Request.QueryString["searchData"] }),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
    {
        HttpMethod = "GET",
        UpdateTargetId = "divRezultat",
        InsertionMode = InsertionMode.Replace
    }))

Views/Financiar/_Detalii.cshtml

<script src="~/Scripts/jquery-3.4.1.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>

<p>
    @Ajax.ActionLink("Afișează vânzări", "Vanzari", "Financiar", new { idMoneda = ViewBag.idMoneda},
                    new AjaxOptions()
                    {
                        HttpMethod = "GET",
                        UpdateTargetId = "divRezultat",
                        InsertionMode = InsertionMode.Replace
                    }, new { @class = "btn btn-primary" }
    )
    <span> </span>
    @Ajax.ActionLink("Afișează cumpărări", "Cumparari", "Financiar", new { idMoneda = ViewBag.idMoneda },
                    new AjaxOptions()
                    {
                        HttpMethod = "GET",
                        UpdateTargetId = "divRezultat",
                        InsertionMode = InsertionMode.Replace
                    }, new { @class = "btn btn-primary" }
    )
</p>

<hr />


<div id="divRezultat">
    @{
        Html.RenderAction("Vanzari", "Financiar", new { idMoneda = ViewBag.idMoneda});
    }
</div>

Views/Financiar/_Vanzari.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<CRYPTO_Burcea.DAL.Tranzactionare>

<script src="~/Scripts/jquery-3.4.1.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>


<p>
    Total vânzări: <b style="color:blue">@ViewBag.suma</b>
</p>
<p>
    Total comisioane: <b>@ViewBag.comisioane euro</b>
</p>

<div class="table-bordered">
    <h4>&nbsp;Căutare</h4>


    @using (Ajax.BeginForm("Vanzari", "Financiar", new { idMoneda = ViewBag.id }, new AjaxOptions()
    {
        HttpMethod = "GET",
        UpdateTargetId = "divRezultat",
        InsertionMode = InsertionMode.Replace
    }))
    {
        <span>&nbsp;Data: </span>@Html.TextBox("searchData", null, new { @class = "form-control datepicker" })
        <input type="submit" class="btn btn-primary" value="Caută" />
    }
    <br />
</div>

<link href="~/Content/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/bootstrap-datepicker.min.js"></script>


<script>
    $('.datepicker').datepicker({
        format: 'yyyy-mm-dd'
    });
</script>


<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().DataTranzactionare)
        </th>
        <th >
            @Html.DisplayName("Suma corespondentă")
        </th>
        <th>
            @Html.DisplayName("Suma vândută")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().ComisionEuro)
        </th>
        <th>
            @Html.DisplayName("Moneda corespondentă")
        </th>
        <th>
            @Html.DisplayName("Moneda vândută")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DataTranzactionare)
            </td>
            <td style="color:green">
                @Html.DisplayFor(modelItem => item.SumaVanduta)
            </td>
            <td style="color:red">
                @Html.DisplayFor(modelItem => item.SumaCumparata)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ComisionEuro)
            </td>
            <td style="color:green">
                @Html.DisplayFor(modelItem => item.Moneda.DenumireMoneda)
            </td>
            <td style="color:red">
                @Html.DisplayFor(modelItem => item.Moneda1.DenumireMoneda)
            </td>
        </tr>
    }

</table>

Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) din @Model.PageCount
@Html.PagedListPager(Model, pagina => Url.Action("Vanzari", "Financiar", new { idMoneda = ViewBag.id, pagina, searchData = Request.QueryString["searchData"] }),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
    {
        HttpMethod = "GET",
        UpdateTargetId = "divRezultat",
        InsertionMode = InsertionMode.Replace
    }))