Controllers/MonedaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRYPTO_Burcea.BLL;
using CRYPTO_Burcea.DAL;
using PagedList;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System.Web.Script.Services;
using System.Web.Services;

namespace CRYPTO_Burcea.Controllers
{
    public class MonedaController : Controller
    {
        BLLMoneda oBLL = new BLLMoneda();
        BLLCursMoneda oBLLc = new BLLCursMoneda();
        BLLDisponibil oBLLd = new BLLDisponibil();
        BLLTranzactionare oBLLt = new BLLTranzactionare();

        // GET: Moneda

        // Actiune afisare monede
        [Authorize]
        public ActionResult Index(string searchDenumire, int? pagina)
        {
            List<Moneda> sursadate;
            IQueryable<Moneda> sursa;
            sursa = oBLL.Afiseaza();
            if (!string.IsNullOrEmpty(searchDenumire))
            {
                sursa = oBLL.Cauta(sursa, m => m.DenumireMoneda.Contains(searchDenumire));
            }

            sursadate = sursa.OrderBy(m => m.DenumireMoneda).ToList();
            return View(sursadate.ToPagedList(pagina ?? 1, 5));
        }

        // Detalii moneda
        [Authorize]
        public ActionResult Detalii(Int64 idMoneda)
        {
            Moneda monedadetalii = oBLL.Detalii(idMoneda);
            ViewBag.Moneda = monedadetalii.DenumireMoneda;


            // GRAFIC
            CRYPTOEntities bd = new CRYPTOEntities();
            var cursuri = bd.Monedas.Where(m => m.Id == idMoneda).Select(m => new { data = m.DataIntrare.ToString(), curs = m.CursIntrare }).ToList();
            var cursuriafter = bd.Curs.Where(c => c.IdMoneda == idMoneda).OrderBy(c => c.DataCurs).ThenBy(c => c.OraCurs).Select(c => new {data = c.DataCurs.ToString(), curs = c.Curs }).ToList();
            foreach(var curs in cursuriafter)
            {
                cursuri.Add(curs);
            }

            ViewBag.DataPoints = JsonConvert.SerializeObject(cursuri, _jsonSetting);

            return View(monedadetalii);
        }
        JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };

        // Editeaza moneda - get(Afisare)
        [Authorize]
        public ActionResult Editeaza(Int64 idMoneda)
        {
            Moneda monedademodificat = oBLL.Detalii(idMoneda);
            ViewBag.Moneda = monedademodificat.DenumireMoneda;
            return View(monedademodificat);
        }

        // Editeaza moneda - post(Executare)
        [Authorize]
        [HttpPost]
        public ActionResult Editeaza(Moneda monedademodificat)
        {
            oBLL.Modifica(monedademodificat);
            return RedirectToAction("Index", "Moneda");

        }

        // Adauga moneda - get(Afisare)
        [Authorize]
        public ActionResult Adauga()
        {
            List<string> referinte = new List<string>();
            referinte.Add("Euro");
            ViewBag.ListaR = referinte.Select(r => new SelectListItem()
            {
                Value = r,
                Text = r
            });
            Moneda monedanoua = new Moneda();
            return View(monedanoua);
        }

        // Adauga moneda - post(Executare)
        [Authorize]
        [HttpPost]
        public ActionResult Adauga(Moneda monedanoua)
        {
            oBLL.Adauga(monedanoua);
            return RedirectToAction("Index", "Moneda");
        }

        // Stergere moneda
        [Authorize]
        public ActionResult Sterge(Int64 idMoneda)
        {
            oBLL.Sterge(idMoneda);
            return RedirectToAction("Index", "Moneda");
        }

        

        






        // Afisare cursuri
        [Authorize]
        public ActionResult IndexCurs(Int64 idMoneda, string searchData, int? pagina)
        {
            ViewBag.id = idMoneda;
            ViewBag.Diferente = oBLLc.DiferentaCurs(idMoneda);
            //IQueryable<Cur> sursa = oBLLc.Afiseaza(idMoneda);
            //return PartialView("_IndexCurs", sursa);


            List<Cur> sursadate;
            IQueryable<Cur> sursa;
            sursa = oBLLc.Afiseaza(idMoneda);
            if (!string.IsNullOrEmpty(searchData))
            {
                DateTime data = Convert.ToDateTime(searchData);
                sursa = oBLLc.Cauta(sursa, c => c.DataCurs == data);
            }
            sursadate = sursa.OrderByDescending(c => c.DataCurs).ThenByDescending(c => c.OraCurs).ToList();

            return PartialView("_IndexCurs", sursadate.ToPagedList(pagina ?? 1, 5));
        }

        // Adauga curs - get(Afisare)
        [Authorize]
        public ActionResult AdaugaCurs(int idMoneda)
        {
            Cur cursnou = new Cur();
            cursnou.IdMoneda = idMoneda;
            cursnou.ColectieMonede = oBLLc.ListaMonede();
            return View(cursnou);
        }

        // Adauga curs - post(Executare)
        [Authorize]
        [HttpPost]
        public ActionResult AdaugaCurs(Cur cursnou)
        {
            oBLLc.Adauga(cursnou);
            return RedirectToAction("Detalii", "Moneda", new { idMoneda = cursnou.IdMoneda});
        }

        // Stergere curs
        [Authorize]
        public ActionResult StergeCurs(Int64 idCurs)
        {
            CRYPTOEntities bd = new CRYPTOEntities();
            int idMoneda = (int)bd.Curs.Where(c => c.Id == idCurs).Select(c => c.IdMoneda).FirstOrDefault();
            oBLLc.Sterge(idCurs);
            return RedirectToAction("Detalii", "Moneda", new { idMoneda = idMoneda });
        }






        // Afisare dispnibil
        [Authorize]
        public ActionResult IndexDisponibil(Int64 idMoneda)
        {
            ViewBag.id = idMoneda;
            ViewBag.Disponibil = oBLL.SoldMoneda(idMoneda);
            IQueryable<Disponibil> sursa = oBLLd.Afiseaza(idMoneda);
            return PartialView("_IndexDisponibil", sursa);
        }

        // Editeaza disponibil - get(Afisare)
        [Authorize]
        public ActionResult EditeazaDisponibil(Int64 idDisponibil)
        {
            Disponibil disponibildemodificat = oBLLd.Detalii(idDisponibil);
            ViewBag.Moneda = disponibildemodificat.Moneda.DenumireMoneda;
            disponibildemodificat.DataModificare = DateTime.Today.Date;
            disponibildemodificat.OraModificare = DateTime.Now.TimeOfDay;
            disponibildemodificat.ColectieMonede = oBLLd.ListaMonede();
            return View(disponibildemodificat);
        }

        // Editeaza moneda - post(Executare)
        [Authorize]
        [HttpPost]
        public ActionResult EditeazaDisponibil(Disponibil disponibildemodificat)
        {
            disponibildemodificat.DataModificare = DateTime.Today.Date;
            disponibildemodificat.OraModificare = DateTime.Now.TimeOfDay;
            oBLLd.Modifica(disponibildemodificat);
            return RedirectToAction("Detalii", "Moneda", new { idMoneda = disponibildemodificat.IdMoneda });

        }




        // Afisare dropdownbox de unde putem alege un portofel pentru care vom cumpara moneda
        [Authorize]
        public ActionResult IndexAlegePortofel(Int64 idMoneda)
        {
            ViewBag.id = idMoneda;
            string username = User.Identity.GetUserName();
            List<ContinutPortofel> continutPortofele = oBLLt.ListaContinutPortofele(username);
            ViewBag.Lista = continutPortofele.Where(c => c.IdMoneda == idMoneda).ToList().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Portofel.DenumirePortofel
            });
            return PartialView("_IndexAlegePortofel");
        }



    }
}

Controllers/TranzactionareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRYPTO_Burcea.DAL;
using CRYPTO_Burcea.BLL;
using Microsoft.AspNet.Identity;

namespace CRYPTO_Burcea.Controllers
{
    public class TranzactionareController : Controller
    {
        BLLTranzactionare oBLL = new BLLTranzactionare();

        // GET: Tranzactionare

        
        public ActionResult Index()
        {
            return View();
        }


        // Adauga tranzactionare - get(Afisare)
        [Authorize]
        public ActionResult Adauga(int idCPortofel, string tipT)
        {
            CRYPTOEntities bd = new CRYPTOEntities();
            ContinutPortofel cPortofel = bd.ContinutPortofels.Find(idCPortofel);
            ViewBag.idP = cPortofel.IdPortofel;
            ViewBag.tipT = tipT;
            ViewBag.Moneda = cPortofel.Moneda.DenumireMoneda;
            TempData["idCP"] = idCPortofel;
            TempData["idM"] = cPortofel.IdMoneda;
            TempData["tipT"] = tipT;
            TempData["moneda"] = cPortofel.Moneda.DenumireMoneda;
            TempData["idP"] = cPortofel.IdPortofel;

            Tranzactionare tranzactionarenoua = new Tranzactionare();
            if (tipT.Equals("Cumparare"))
            {
                tranzactionarenoua.IdContinutPortofelCumparare = idCPortofel;
                tranzactionarenoua.IdMonedaCumparata = cPortofel.IdMoneda;
                tranzactionarenoua.DataTranzactionare = DateTime.Today.Date;
                string username = User.Identity.GetUserName();
                tranzactionarenoua.ColectieContinutPortofeleC = oBLL.ListaContinutPortofele(username);
                tranzactionarenoua.ColectieMonedeC = oBLL.ListaMonede(username);


                List<ContinutPortofel> continutPortofele = oBLL.ListaContinutPortofele(username);
                int idMoneda = (int)cPortofel.IdMoneda;
                tranzactionarenoua.ColectieContinutPortofeleV = continutPortofele.Where(c => c.IdMoneda != idMoneda).ToList();

                List<Moneda> monede = oBLL.ListaMonede(username);
                Moneda mnd = monede.First(m => m.Id == idMoneda);
                monede.Remove(mnd);
                tranzactionarenoua.ColectieMonedeV = monede;
            }
            else if (tipT.Equals("Vanzare"))
            {
                tranzactionarenoua.IdContinutPortofelVanzare = idCPortofel;
                tranzactionarenoua.IdMonedaVanduta = cPortofel.IdMoneda;
                tranzactionarenoua.DataTranzactionare = DateTime.Today.Date;
                string username = User.Identity.GetUserName();
               

                List<ContinutPortofel> continutPortofele = oBLL.ListaContinutPortofele(username);
                int idMoneda = (int)cPortofel.IdMoneda;
                tranzactionarenoua.ColectieContinutPortofeleC = continutPortofele.Where(c => c.IdMoneda != idMoneda).ToList();

                List<Moneda> monede = oBLL.ListaMonede(username);
                Moneda mnd = monede.First(m => m.Id == idMoneda);
                monede.Remove(mnd);
                tranzactionarenoua.ColectieMonedeC = monede;

                tranzactionarenoua.ColectieContinutPortofeleV = oBLL.ListaContinutPortofele(username);
                tranzactionarenoua.ColectieMonedeV = oBLL.ListaMonede(username);
            }
            return View(tranzactionarenoua);
        }

        // Adauga tranzactionare - post(Executare)
        [Authorize]
        [HttpPost]
        public ActionResult Adauga(Tranzactionare tranzactionarenoua)
        {
            int idCP = (int)TempData["idCP"];
            int idM = (int)TempData["idM"];
            string tipT = (string)TempData["tipT"];
            string denumiremoneda = (string)TempData["moneda"];
            int idP = (int)TempData["idP"];

            if (tipT.Equals("Cumparare"))
            {
                tranzactionarenoua.IdContinutPortofelCumparare = idCP;
                tranzactionarenoua.IdMonedaCumparata = idM;
                tranzactionarenoua.DataTranzactionare = DateTime.Today.Date;
            }
            else if (tipT.Equals("Vanzare"))
            {
                tranzactionarenoua.IdContinutPortofelVanzare = idCP;
                tranzactionarenoua.IdMonedaVanduta = idM;
                tranzactionarenoua.DataTranzactionare = DateTime.Today.Date;
            }

            if (ModelState.IsValid)
            {
                CRYPTOEntities bd = new CRYPTOEntities();
                ContinutPortofel cPortofel = bd.ContinutPortofels.Find(idCP);
                oBLL.Adauga(tranzactionarenoua);
                return RedirectToAction("Detalii", "Portofel", new { idPortofel = cPortofel.IdPortofel });
            }
            Tranzactionare tranzactionarenouadinnou = new Tranzactionare();
            if (tipT.Equals("Cumparare"))
            {
                tranzactionarenouadinnou.IdContinutPortofelCumparare = idCP;
                tranzactionarenouadinnou.IdMonedaCumparata = idM;
                tranzactionarenouadinnou.DataTranzactionare = DateTime.Today.Date;
                string username = User.Identity.GetUserName();
                tranzactionarenouadinnou.ColectieContinutPortofeleC = oBLL.ListaContinutPortofele(username);
                tranzactionarenouadinnou.ColectieMonedeC = oBLL.ListaMonede(username);


                List<ContinutPortofel> continutPortofele = oBLL.ListaContinutPortofele(username);
                int idMoneda = idM;
                tranzactionarenouadinnou.ColectieContinutPortofeleV = continutPortofele.Where(c => c.IdMoneda != idMoneda).ToList();

                List<Moneda> monede = oBLL.ListaMonede(username);
                Moneda mnd = monede.First(m => m.Id == idMoneda);
                monede.Remove(mnd);
                tranzactionarenouadinnou.ColectieMonedeV = monede;
            }
            else if (tipT.Equals("Vanzare"))
            {
                tranzactionarenouadinnou.IdContinutPortofelVanzare = idCP;
                tranzactionarenouadinnou.IdMonedaVanduta = idM;
                tranzactionarenouadinnou.DataTranzactionare = DateTime.Today.Date;
                string username = User.Identity.GetUserName();


                List<ContinutPortofel> continutPortofele = oBLL.ListaContinutPortofele(username);
                int idMoneda = idM;
                tranzactionarenouadinnou.ColectieContinutPortofeleC = continutPortofele.Where(c => c.IdMoneda != idMoneda).ToList();

                List<Moneda> monede = oBLL.ListaMonede(username);
                Moneda mnd = monede.First(m => m.Id == idMoneda);
                monede.Remove(mnd);
                tranzactionarenouadinnou.ColectieMonedeC = monede;

                tranzactionarenouadinnou.ColectieContinutPortofeleV = oBLL.ListaContinutPortofele(username);
                tranzactionarenouadinnou.ColectieMonedeV = oBLL.ListaMonede(username);
            }
            TempData["idCP"] = idCP;
            TempData["idM"] = idM;
            TempData["tipT"] = tipT;
            TempData["moneda"] = denumiremoneda;
            TempData["idP"] = idP;
            ViewBag.idP = idP;
            ViewBag.tipT = tipT;
            ViewBag.Moneda = denumiremoneda;
            return View(tranzactionarenouadinnou);
        }






        // Auto completare suma cumparata
        [Authorize]
        public JsonResult AutoCompletareSumaC(string sumaV, string idMC, string idMV)
        {
            int idMonedaCumparata = Convert.ToInt32(idMC);
            int idMonedaVanduta = Convert.ToInt32(idMV);
            decimal sumaVanduta = Convert.ToDecimal(sumaV) - (0.05m * Convert.ToDecimal(sumaV));  //---- COMISION 5%

            // Obtinem ultimul curs al monedei care se doreste a fi cumparata (curs de vanzare pt entitate)
            // si aflam suma cumparata din cealalta moneda
            CRYPTOEntities bd = new CRYPTOEntities();
            decimal curs = 0;
            decimal diferentaVanzare = 0;
            decimal sumaCumparata = 0;
            Moneda monedaCumparata = bd.Monedas.Where(m => m.Id == idMonedaCumparata).FirstOrDefault();
            Moneda monedaVanduta = bd.Monedas.Where(m => m.Id == idMonedaVanduta).FirstOrDefault();
            if (monedaCumparata.DenumireMoneda.Equals(monedaCumparata.Referinta))
            {
                curs = (decimal)bd.Curs.Where(c => c.IdMoneda == idMonedaVanduta).OrderByDescending(c => c.DataCurs).ThenByDescending(c => c.OraCurs).Select(c => c.Curs).FirstOrDefault();
                diferentaVanzare = (decimal)bd.Monedas.Where(m => m.Id == idMonedaVanduta).Select(m => m.DiferentaCumparare).FirstOrDefault();
                curs = Math.Round(curs * (1 + (diferentaVanzare / 100)), 4);

                // Aflare suma cumparata
                sumaCumparata = Math.Round(sumaVanduta * curs, 4);
            }
            else if (monedaVanduta.DenumireMoneda.Equals(monedaVanduta.Referinta))
            {
                curs = (decimal)bd.Curs.Where(c => c.IdMoneda == idMonedaCumparata).OrderByDescending(c => c.DataCurs).ThenByDescending(c => c.OraCurs).Select(c => c.Curs).FirstOrDefault();
                diferentaVanzare = (decimal)bd.Monedas.Where(m => m.Id == idMonedaCumparata).Select(m => m.DiferentaVanzare).FirstOrDefault();
                curs = Math.Round(curs * (1 + (diferentaVanzare / 100)), 4);

                // Aflare suma cumparata
                sumaCumparata = Math.Round(sumaVanduta / curs, 4);
            }
            else
            {
                decimal cursC = (decimal)bd.Curs.Where(c => c.IdMoneda == idMonedaCumparata).OrderByDescending(c => c.DataCurs).ThenByDescending(c => c.OraCurs).Select(c => c.Curs).FirstOrDefault();

Views/Moneda/Adauga.cshtml
@model CRYPTO_Burcea.DAL.Moneda
@using Microsoft.AspNet.Identity
@using CRYPTO_Burcea.BLL

@{
    ViewBag.Title = "Adaugare moneda";
    BLLUtilizator oBLL = new BLLUtilizator();
}

<h2>Adăugare monedă</h2>


@if (oBLL.EsteAdmin(User.Identity.GetUserName()))
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.DenumireMoneda, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DenumireMoneda, new { htmlAttributes = new { @class = "form-control", @placeholder = "Denumirea monedei" } })
                    @Html.ValidationMessageFor(model => model.DenumireMoneda, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataIntrare, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DataIntrare, new { htmlAttributes = new { @class = "form-control", @placeholder = "Data intrarii pe piata" } })
                    @Html.ValidationMessageFor(model => model.DataIntrare, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CursIntrare, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CursIntrare, new { htmlAttributes = new { @class = "form-control", @placeholder = "Curs de intrare" } })
                    @Html.ValidationMessageFor(model => model.CursIntrare, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Referinta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Referinta, new { htmlAttributes = new { @class = "form-control", @placeholder = "Moneda de referinta" } })*@
                    @Html.DropDownListFor(model => model.Referinta, new SelectList(ViewBag.ListaR, "Value", "Text"), "Selectati moneda de referinta", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Referinta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiferentaVanzare, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiferentaVanzare, new { htmlAttributes = new { @class = "form-control", @placeholder = "Diferenta vanzare (%)" } })
                    @Html.ValidationMessageFor(model => model.DiferentaVanzare, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiferentaCumparare, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiferentaCumparare, new { htmlAttributes = new { @class = "form-control", @placeholder = "Diferenta cumparare (%)" } })
                    @Html.ValidationMessageFor(model => model.DiferentaCumparare, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Detalii, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Detalii, new { htmlAttributes = new { @class = "form-control", @placeholder = "Detalii" } })
                    @Html.ValidationMessageFor(model => model.Detalii, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Adaugă" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
}


<div>
    @Html.ActionLink("Înapoi", "Index", "Moneda", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Moneda/AdaugaCurs.cshtml
@model CRYPTO_Burcea.DAL.Cur
@using Microsoft.AspNet.Identity
@using CRYPTO_Burcea.BLL

@{
    ViewBag.Title = "Adaugare curs";
    BLLUtilizator oBLL = new BLLUtilizator();
}

<h2>Adăugare curs</h2>

@if (oBLL.EsteAdmin(User.Identity.GetUserName()))
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IdMoneda, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IdMoneda, new SelectList(Model.ColectieMonede, "Id", "DenumireMoneda"), "Selectati moneda", htmlAttributes: new { @class = "form-control", disabled = "disabled" })
                    @Html.ValidationMessageFor(model => model.IdMoneda, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataCurs, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DataCurs, new { htmlAttributes = new { @class = "form-control", @placeholder = "Data curs" } })
                    @Html.ValidationMessageFor(model => model.DataCurs, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OraCurs, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OraCurs, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ora curs" } })
                    @Html.ValidationMessageFor(model => model.OraCurs, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Curs, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Curs, new { htmlAttributes = new { @class = "form-control", @placeholder = "Curs moneda" } })
                    @Html.ValidationMessageFor(model => model.Curs, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Adaugă" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
}


<div>
    @Html.ActionLink("Înapoi", "Detalii", "Moneda", new { idMoneda = Model.IdMoneda }, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Moneda/_IndexAlegePortofel.cshtml
@*@model CRYPTO_Burcea.DAL.Tranzactionare*@

@using (Html.BeginForm("Adauga", "Tranzactionare", FormMethod.Get))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alegeți portofelul unde doriți să adăugați moneda cumpărată</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <input type="hidden" name="tipT" value="Cumparare" />

        <div class="form-group">
            @Html.Label("Portofel", "Portofel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCPortofel", new SelectList(ViewBag.Lista, "Value", "Text"), "Selectati portofelul ", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessage("idCPortofel", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tranzacționare" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Închide", "Index", "Moneda", null, new { @class = "btn btn-primary"})
</div>